####
POST http://localhost:3005/api/query/one-to-one
Content-Type: application/json

{
    "firstName":"Dilip",
    "lastName":"Kumar"
}

######
POST http://localhost:3005/api/user/add-user-contact
Content-Type: application/json

{ "userId": 1, "contacts": [{"name": "manisha",
"number": "5678322769"},{"name": "sufin", "number": "678965725"}] }



######
GET http://localhost:5000/api/user/common-user/123456789



####
GET http://localhost:5000/api/user/contacts?page=1&pageSize=2
